### ISSUE TITLE
Unable to process UN formatted JSON data

### ISSUE THREAD

**Issue by i-cooltea** [AndrewRedican/react-json-editor-ajrm#89] opened 2018-10-29 09:58 UTC
|Question| Answer|
|--|--|
|version| The Lastest Version|

**No formatted JSON string is detected as an error JSON.
This JSON string does not have any syntax problems. It's just not formatted.**
(It can pass syntax check after formatting.)

Json String like it.
```
{
    "sql": {
        "server": {
			"server1": {
				"class": "yii\\db\\Connection",
				"dsn": "mysql:host=xx;port=xx;dbname=xxxx",
				"username": "xx",
				"password": "xx",
				"charset": "utf8"
            },
			"sql1": "select xx from xx"
		},
		"cmd": "mysql -h___host -u___username -P___port -p___password -D___dbname -A < ___file"
	},
	 "script": {
		"server": {
			"sip": "xx.xx.xx.xx",
			"shost": "xx.xx.xx.xx",
			"suser": "root",
			"sport": 2222,
			"phppath": "/xx/php5/bin/php",
			"webser": "/xx/www/",
			"git": "xx"
		},
		"cmd": "ssh -p ___sport ___suser@___sip ' source /etc/profile && ___phppath ___webser___git/yii ___script --orgcode=xx' "
    }
}
```

**Comment by PatrickSachs** [comment] 2018-10-30 15:23
Hello - thank you very much for reporting this,

I am able to reproduce this on my end. 

Can you attempt to use the workaround described here? https://github.com/AndrewRedican/react-json-editor-ajrm/issues/87

Otherwise this could also be related to too many nested update calls. We'll look into this once possible.

**Comment by ADirtyCat** [comment] 2018-10-31 01:37
The error is not related to double quotation marks. It looks like indentation and space.

**Comment by PatrickSachs** [comment] 2018-10-31 15:18
I see. There seems to be something seriously wrong with parsing in the current release.

We're currently waiting for #83 to be merged before making any further changes to this logic, as the PR changes a huge portion of the code base.

Thank for for reporting this. I'll mark the issue as high priority, but cannot guarantee that it will be fixed in the next three days as the label would normally indicate.

**Comment by AndrewRedican** [comment] 2023-01-29 03:28
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.

**Closed by AndrewRedican** 2023-01-29 03:28 UTC
Labels: bug, high priority
