### ISSUE TITLE
Failed to build this code within create-react-app

### ISSUE THREAD

**Issue by PetrykowskiM** [AndrewRedican/react-json-editor-ajrm#51] opened 2018-08-29 09:01 UTC
1. What version of RJEA are you using (react-json-editor-ajrm version)?
^2.5.3
2. What operating system and processor architecture are you using?
Mac
3. What did you do?
Integrated it into 
4. Problem
Create-React-App is an easy way to get started with react apps of any kind. I just created a new side project where I used `react-json-editor-ajrm`. Since I wanted to deliver the frontend through a dockerfile I built the project by using react-scripts.
However this creates the following error:
```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-json-editor-ajrm/es/index.js:12

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

**Comment by PatrickSachs** [comment] 2018-08-29 09:11
Hello @PetrykowskiM 

since it's the same error message, I suspect this is a duplicate of #40. Let us know if this works out for you.

**Comment by PetrykowskiM** [comment] 2018-08-29 10:13
Thanks! That worked out for me.

**Comment by AndrewRedican** [comment] 2018-08-29 15:35
@PetrykowskiM, glad that worked!

@PatrickSachs,

Since this is a common question, it would be worthwhile adding a second example, using react-create-app, or at the very least, put somewhere in the readme about these differences. 🤔 

What do you think?

**Comment by PatrickSachs** [comment] 2018-08-29 16:44
Yeah, I think adding a section to the readme might be a good idea.

Would you think that a possible create-react-app sample would belong in this repo, or should it be a second example repo?

**Comment by AndrewRedican** [comment] 2018-08-29 17:06
If by "repo" you refer to both Github and NPM, then I think this new example should not be available on a separate repo. I think this example is still relevant to the project, so we should keep it in Github. As for NPM -I am not sure how much of a positive impact is having a separate NPM example repo like were currently do.

We would probably move the existing example to a directory named something like `/examples/NameOfExample`, and add an additional subdirectory under `/examples` for a react-create-app set up.

**Comment by PatrickSachs** [comment] 2018-08-29 17:12
Makes sense, that sounds like a good idea.

**Comment by PetrykowskiM** [comment] 2018-08-30 07:49
@AndrewRedican I created a PR for that. https://github.com/AndrewRedican/react-json-editor-ajrm/pull/52

**Closed** 2018-08-30 23:03 UTC
Labels: duplicate
