### ISSUE TITLE
Performance problems with large datasets

### ISSUE THREAD

**Issue by ntfs32** [AndrewRedican/react-json-editor-ajrm#75] opened 2018-10-08 07:01 UTC
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.6
2. What operating system and processor architecture are you using? *REQUIRED
MacOS ,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
3. What did you do? *REQUIRED
input a big json string,more than 1500 rows.
4. What did you expect to see? *REQUIRED
select all json string after ajrm formated, can not delete theme, the chrome page will be die.
5. What did you see instead? *REQUIRED
delete big json ok.

**Comment by PatrickSachs** [comment] 2018-10-09 16:49
Hello @ntfs32 

I can reproduce the issue on my end.

> input a big json string

How did you input the JSON string? Did you use it as a placeholder, or did you paste it in?
It seems like the component always crashes when pasting data into it, regardless of how large it is. This is certainly is a new bug since copy pasting used to work just fine before.
Does it crash for you even with small amounts of pasting?

> can not delete theme

I don't quite understand, I'm sorry. Could you explain this a bit more?

Thank you for providing some additional intel.

**Comment by ntfs32** [comment] 2018-10-10 02:56
@PatrickSachs  Thank you for your quick reply.  
I tried it again.  Just copy pasting input a big json string, then select it and delete, It will be very slow. It will be delete, but 1500 lines took more than 50 seconds.

**Comment by Patrick-Sachs** [comment] 2018-10-10 07:02
@ntfs32 Got it, thank you! In this case #78 should be the PR that fixes this. I

f you can spare the time, please try cloning the "no-id" branch of this repo and launch either the webpack or create-react-app example and see how it behaves.

**Comment by ntfs32** [comment] 2018-10-10 09:53
function  createRef Not support react 15...
i think callback ref will be more friendly.

**Comment by Patrick-Sachs** [comment] 2018-10-10 11:13
Thanks for the feedback. I'll look into it.

**Comment by PatrickSachs** [comment] 2018-10-12 16:50
Hello @ntfs32 - Could you please try if the issue persists in ^2.5.7?

**Comment by royderksroute42** [comment] 2018-11-19 09:41
I can confirm that this still is an issue. Copy-pasting a JSON string into the field freezes the entire tab, making it impossible to close it even. Using ^2.5.8.

**Comment by Pabsz** [comment] 2022-09-14 12:37
Not sure why this issue is closed. Large JSON, regardless of copy paste or not, causes performance issue and freezes my tab. I'm not copy pasting anything into the editor, in my case I'm simply using the placeholder props.

**Comment by mateodelnorte** [comment] 2022-12-29 21:14
Has anyone found a solution for this?

**Comment by AndrewRedican** [comment] 2022-12-29 21:47
@Pabsz  @mateodelnorte @royderksroute42

Hey, all I am aware of this issue since day one. It's been tough to find work-life balance the last few years, had some life-changing events, etc. Slowly things are getting a bit quieter for me, with a bit of time. I've got 81 emails regarding issues with this projects, I intend to go through.

I plan to fix this issue. The problem is it'll probably require rewrite from the ground up. Watch this space: https://github.com/enio-ireland which is where I am going to put it. ETA is roughly one or two months. So don't hold your breath. However, if anyone has forked this project, feel free to give this a try.

The gist of how I plan to fix:

1. Use [webworks](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to do the parsing in a separate thread from the main UI thread.
2. Also looking into diving up the parsing in chunks, and lazy render (meaning brackets could be collapsed or expanded and only then rendered in the screen.
3. Virtually scrolling to only render the elements that would be in view. Admitted a more complicated optimization, would be opt-in as it would have some caveats as items not being searchable.

**Closed by AndrewRedican** 2022-12-29 21:47 UTC
Labels: bug
