### ISSUE TITLE
Using html tags within JSON string are rendered in the form and as a result invalid JSON

### ISSUE THREAD

**Issue by joe-at-startupmedia** [AndrewRedican/react-json-editor-ajrm#32] opened 2018-07-31 15:34 UTC
1. What version of RJEA are you using (react-json-editor-ajrm version)?
"react-json-editor-ajrm": "^2.4.7",
2. What operating system and processor architecture are you using?
Mac
3. What did you do?
Add <br/ > tags to a json string
4. What did you expect to see?
The <br /> tags not rendered.
5. What did you see instead?
The <br /> tags were rendered and as a result the json became invalid.

**Comment by AndrewRedican** [comment] 2018-07-31 15:37
Hi @joe-at-startupmedia, this should be a quick fix. 

I will be providing an update shortly.

**Comment by AndrewRedican** [comment] 2018-08-02 05:16
Hey @joe-at-startupmedia,

I was looking into your issue. I could not replicate the problem. A similar issue was addressed in earlier versions https://github.com/AndrewRedican/react-json-editor-ajrm/issues/19.

1. Typing <br/> directly works.
2. Adding <br/> inside a key or string notitation even within an javascript object passed through `this.props.placeholder` is rendering correctly.

If either of the above describes the intended behavior, I would suggest getting the latest version of the component. Most likely this will resolve the issue.

If you still have issues after updating to the latest version, please expand on the reproduction steps so I can better assist you.

===== 

Upon following up on your issue, I did notice something else. Upon pasting contents from clipboard into component, will result in all html tags removed. See https://github.com/AndrewRedican/react-json-editor-ajrm/issues/34.

**Comment by AndrewRedican** [comment] 2018-08-02 18:45
Thanks Joe. I am closing this issue in favor of the one I created.

**Closed by AndrewRedican** 2018-08-02 18:45 UTC
Labels: high priority, more info needed
