### ISSUE TITLE
How to render JSON?

### ISSUE THREAD

**Issue by ujovlado** [AndrewRedican/react-json-editor-ajrm#71] opened 2018-10-05 15:40 UTC
> 1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED

2.5.5

> 2. What operating system and processor architecture are you using? *REQUIRED

not important

> 3. What did you do? *REQUIRED

set JSON to `placeholder` property

> 4. What did you expect to see? *REQUIRED

JSON in editor

> 5. What did you see instead? *REQUIRED

nothing

Since this is a JSON editor, why is it not possible to enter a JSON string to placeholder? Or at least have an option to set "data type" to JSON?

The problem is that placeholder accepts only JS object and editor renders it as JS object (which is correct), but what if you want to display JSON, since user is editing JSON, not JS object?

**Comment by PatrickSachs** [comment] 2018-10-05 15:53
Hello @ujovlado,

I can understand your confusion. As of now this component only supports JS-objects, not pure JSON objects. Support for JSON5(and other languages) is currently in planning: #50 

However, I believe that exposing the default behaviour to users is not an issue since they cannot write anything dangerous(such as functions) or things that could not be serialized to "real" JSON(such as `undefined`) afterwards in it anyways.

**Comment by AndrewRedican** [comment] 2018-10-07 21:32
I believe we have provided a suitable answer to your inquiry. However, we have not heard from you in a while, thus I am closing this now. See [policy](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/CONTRIBUTING.md#timely-confirmation-policy-all-answered-inquiries-must-be-confirmed-in-a-timely-manner). Feel free to open up a new issue should you have more inquiries.

**Closed by AndrewRedican** 2018-10-07 21:32 UTC
Labels: inquiry

**Comment by ujovlado** [comment] 2018-10-08 12:41
Ok, thanks for explanation.
