### ISSUE TITLE
Workflow for integration with redux

### ISSUE THREAD

**Issue by cgvedant** [AndrewRedican/react-json-editor-ajrm#62] opened 2018-09-19 20:00 UTC
1. What version of RJEA are you using (react-json-editor-ajrm version)? v2.5.4
2. What operating system and processor architecture are you using? macOS 10.13.6
3. What did you do? Use redux to store object and update it with RJEA using onChange
4. What did you expect to see? Some way to get it to work
5. What did you see instead? Unwanted/premature updates due to order of steps taken.

This is going to be a bit long, so TLDR:

- In the [update](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L506) function it would be better to fetch the cursorPosition before calling onChange().
- Why are we calling showPlaceHolder() in [componentDidUpdate](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L595)?

Hi, I have a stringified JSON which I'm storing in a redux store. I wanted to make it editable as a string, so I've added the appropriate reducer which takes the new string (I was previously using \<input \/\> to edit it) and replaces it in the redux store.
I've been trying to find a way to use RJEA instead of \<input\/\> for a better experience, but I'm unable to find the correct way to do it. So I'd like to know if there is an expected method, or if it is not yet an intended use case.

The first problem I've faced is with the cursor jumping to the start after every update(). The reason this happens is we are calculating the cursor position on [Line 519](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L519), but before this happens onChange is being called on [Line 511](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L511). This causes a dispatch which results in a re-render. After this re-render the cursorPosition calculated by getCursorPosition is 0 (I'm guessing this is due to loss of focus as a result of change in render count). I see no reason why we would want to postpone the computing of cursor position until after the onChange() executes. So calling getCursorPosition before onChange would satisfy my use case without causing any breaking changes.

The README mentions that placeholder will be shown once when the component is mounted. The function responsible to do this - [showPlaceholder](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L611) is not only being used in [componentDidMount](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L606) but also in [componentDidMount](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L599). This seems to contradict what's mentioned in the README. Whenever I'm doing some edits and the clicking out side the component (causing a blur) I lose edits that were made.

I haven't read through the whole tokenize() function but it looks like if it's not a DOM node the 'something' object would just be stringified and used. Since what is shown in the component is also an editable string I feel it would be better if we also accepted a stringified JSON as placeholder. This would enable us to use the component to find errors/edit incorrect/incomplete JSON strings. I'm not sure if it's as easy as just removing the [JSON.stringify](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L1534) or if it involves more complex error state building.

Another thing I wanted to ask was are randomString() and renderCount() really necessary. I've had to use the 'test' prop because my server-side ID wasn't matching browser ID due to the un-seeded random. The IDs anyway don't seem to be used by react for anything substantial. Am I missing something?

**Comment by AndrewRedican** [comment] 2018-09-19 20:38
Hi @cgvedant,

Thanks for being this thorough with your inquiries. I will be answering your inquiries to the best of my abbility one at a time in no particular order.

**Comment by AndrewRedican** [comment] 2018-09-19 21:11
> Another thing I wanted to ask was are `randomString()` and `renderCount()` really necessary. I've had to use the 'test' prop because my server-side ID wasn't matching browser ID due to the un-seeded random. [...]

It all boils down to the use `contentEditable` tag or attribute in the DOM element that contains the content of this component. For reasons that go beyond the scope of this question, and to keep it short, we ought to use `contentEditable` as opposed other possible options. I've been down this road for months and come to the conclusion we must use `contentEditable` tag. However div or span elements don't come with some built-in event listeners like [onChange](https://developer.mozilla.org/en-US/docs/Web/Events/change) and [onInput](https://developer.mozilla.org/en-US/docs/Web/Events/input) that an `input`, a `select` or a `textarea` element would have, making a controlled component much more complex. This project conciously makes use of the `contentEditable` tag and tries to work around its pitfalls which may not be perfect, but get the job done.

The reason behind requiring an id property has to do with how we need to provide html markup as string into the innerHtml attribute of the `contentEditable` element, as opposed to providing children elements, which we are used to in React. We need ids for each element to listen to and/or target that element for changes.

The reason behind appending a random string to the `uinqueID` is to make sure that eventListeners created upon mounting this component's DOM elements will remain unique and point to the corresponding RJEA component they were created for.

I know understand first-hand how randomness in an element's id can be difficult. I did experience issues when setting up unit testing, which would look at the id which would not match. Hence the property `test` which I see you used.

A quick solution would be to provide users for a property to opt out of the default behaviour of appending a random string to the id property that is used internaly (what `test` property is doing already). I am open to other suggestions, as long as they can guarantee me each id will be unique for any two or more RJEA components.

**Comment by AndrewRedican** [comment] 2018-09-19 21:48
> The README mentions that placeholder will be shown once when the component is mounted. The function responsible to do this - showPlaceholder is not only being used in componentDidMount but also in componentDidMount. This seems to contradict what's mentioned in the README. Whenever I'm doing some edits and the clicking out side the component (causing a blur) I lose edits that were made.

You repeated `componentDidMount()` twice but I asume the second time you were actually referring to `componentDidUpdate()` right? `showPlaceholder()` also shows up in `componentDidUpdate()` because we want to make sure that, whenever you pass a different value to `placeholder` property, the component will render it to the screen as well.

Imagine if you had a dropdown to chose between different data samples to display, and depending on which option you'd chose RJEA would show it on screen. Well, if `showPlaceholder()` wasnt included in `componentDidUpdate()`, nothing different would be rendered.

For the sake of completeness, remember properties passed to RJEA are in a "pre-processed" state. The `tokenize()` functions processes _something_ into the actual values that the component would use. These values are assigned internally, via `this.` -and these values will not automatically change whenever the RJEA properties are updated. I need to call `tokenize()` or in other words `showPlacerholder()` for that to happen. For the sake of completeness, this also applies to `updateInternalProps()`.

In addition to that `showPlacerholder()` in `componentDidUpdate()` unless there has been an actual change in the placeholder property. In other words, it will not execute unnecessarily.

There also a reason why this function was placed in `componentDidUpdate()` rather a different React component life cycle method, which scopes out of the question.

**Comment by AndrewRedican** [comment] 2018-09-19 21:54
> The first problem I've faced is with the cursor jumping to the start after every update(). The reason this happens is we are calculating the cursor position on Line 519, but before this happens onChange is being called on Line 511. This causes a dispatch which results in a re-render. After this re-render the cursorPosition calculated by getCursorPosition is 0 (I'm guessing this is due to loss of focus as a result of change in render count). I see no reason why we would want to postpone the computing of cursor position until after the onChange() executes. So calling getCursorPosition before onChange would satisfy my use case without causing any breaking changes.

I know there are some issues with cursor focusing. I have fixed some of them. I'd would like to review your particular use case in detail before making any changes to the cursor positioning behavior. Can you provide a trimmed working example (with redux) so I can help you out?

**Comment by cgvedant** [comment] 2018-09-20 05:49
> Imagine if you had a dropdown to chose between different data samples to display, and depending on which option you'd chose RJEA would show it on screen. Well, if `showPlaceholder()` wasnt included in `componentDidUpdate()`, nothing different would be rendered.

Ok, so the purpose of placeholder is to act as the initial object which we work upon. In that case, I think the definition in the README should be changed from 'Send a valid javascript object to be shown once when component is mounted' to something which indicates that the object will be referenced not only when the component is mounted, but also when the component is updated.
There could be a case where I'm calling JSONInput with placeholder=JSON.parse('{"name": "Bob"}'). In this case, two parses a=JSON.parse() and b=JSON.parse() will always result in a != b. So any change in the parent component would lead to JSONInput reloading the placeholder. I think a flag that controls whether we ignore the placeholder prop after mounting would be useful. Then again, supporting a sting placeholder along with this flag could cause problems.

**Comment by AndrewRedican** [comment] 2018-09-21 10:15
> I think the definition in the README should be changed [...]

I've updated the documentation for `placeholder` property. Again, thanks for your input. Check it out https://github.com/AndrewRedican/react-json-editor-ajrm/commit/18345ce4cff1e41819d9461358a51d71ce9eefc6. Let me know if this looks good.

**Comment by AndrewRedican** [comment] 2018-09-21 10:19
> There could be a case [...]

Lets move this bit of the conversation to this issue https://github.com/AndrewRedican/react-json-editor-ajrm/issues/64.

**Comment by cgvedant** [comment] 2018-09-21 13:46
Shall I open another issue requesting support for string placeholder?

> > I haven't read through the whole tokenize() function but it looks like if it's not a DOM node the 'something' object would just be stringified and used.
> 
> That is correct.

Should I try to see if this works and submit a PR?

**Comment by AndrewRedican** [comment] 2018-09-21 15:43
@cgvedant,
Feel free to submit a PR.

Also, check on my response on the other issue or pull the latest changes from master.

**Comment by AndrewRedican** [comment] 2018-09-27 21:14
I am closing this as it has been a while since we have seen any development in this conversation. I presume you were waiting for feedback on your previous pull-request. Sorry it took that long. You've raised some interesting suggestions, I will be submitting a pull request of my own.

Feel free to open a pull request to add a feature to handle json as placeholder value instead of a javascript object. I remember now the reason we accept only a javascript object for the `placeholder` property. That is because we would like to separate errors from incoming incorrect json, and actual errors originated from within the component.

At the moment you would have to parse the json string before sending it to the `placeholder` property -this is meant by design. Should a JSON.parse fail, outside RJEA component, it will be clear to determine the error. If you do submit a PR to support JSON string a placeholder, please be sure to address how we can clearly show where the error comes from.

**Closed by AndrewRedican** 2018-09-27 21:14 UTC
Labels: inquiry
